### ISSUE TITLE
Stuck At "Getting the song ready for you..."

### ISSUE THREAD

**Issue by ArmagdoGaming** [deepjyoti30/ytmdl-web-v2#12]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues. (I did, but there were no logs there.)
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <Brave>
- Version: (Latest version.)

## Console Log

[ytmdl.deepjyoti30.dev-1617700747017.log](https://github.com/deepjyoti30/ytmdl-web-v2/files/6263511/ytmdl.deepjyoti30.dev-1617700747017.log)
[ytmdl.deepjyoti30.dev-1617700737488.log](https://github.com/deepjyoti30/ytmdl-web-v2/files/6263512/ytmdl.deepjyoti30.dev-1617700737488.log)

## Description

I can't download anything. It always gets stuck at "Getting the song ready for you..." without progressing further.

## Expected Behaviour

The expected behaviour is that the song gets downloaded...?

**Comment by deepjyoti30** [comment]
@ArmagdoGaming I took a look at the log files you provided. It seems like everything is fine.

I have some questions for you:

1. How many times have you faced this issue?
2. How long did you wait before you considered it "stuck". Sometimes, it is possible that it takes a bit of time to download since the backend gets a lot of requests at the same time.
3. How many songs have you tried downloading and faced this issue with?
4. Were you not able to download any song at all since you tried or did it work, at least once?

Also, I just tried downloading a song myself and it worked without any issues. I have to admit it took a bit of time (about `25 seconds`) on the loading screen but it did work all right.

**Comment by ArmagdoGaming** [comment]
@deepjyoti30 
> 1. How many times have you faced this issue?
A lot. I think the app has only worked once for me.
> 2. How long did you wait before you considered it "stuck". Sometimes, it is possible that it takes a bit of time to download since the backend gets a lot of requests at the same time.
I give it an average of around 5-10 minutes. But, sometimes I wait for over 15 minutes,
> 3. How many songs have you tried downloading and faced this issue with?
A lot. Arount 15-25 songs. I have first heard about this through a relatively old Reddit post, around 2-3 months old, and have been trying to download songs on the site since then, but only managed to download from it once.
> 4. Were you not able to download any song at all since you tried or did it work, at least once?
I did download a song once, and that's it.
>Also, I just tried downloading a song myself and it worked without any issues. I have to admit it took a bit of time (about 25 seconds) on the loading screen but it did work all right.
If I had to wait 25 seconds, or a minute to use this app, I would absolutely do it. The problem is that I wait, and nothing happens.

I'll let it run overnight, and check back to see if it gets fixed or not.
If something that I have said could lead to a quick fix, or a specific problem that I have, please, feel free to reply to me.

**Comment by ArmagdoGaming** [comment]
Alright. Seems to be working now. Just took a while to get the song ready. Around 25-30 minutes, but it worked.

**Comment by ArmagdoGaming** [comment]
Never mind. It got me to the download page, but now there is a new error, and in the console it has "If you can see this error, report it!"

[ytmdl.deepjyoti30.dev-1617741038544.log](https://github.com/deepjyoti30/ytmdl-web-v2/files/6267413/ytmdl.deepjyoti30.dev-1617741038544.log)

**Comment by deepjyoti30** [comment]
@ArmagdoGaming Looking at the logs it seems like the file was ready in the server however it didn't work while trying to download.

Even though the servers are not able to handle requests, it is very weird that it took them 25-30 mins. May I know how long the song was that you tried to download? Perhaps a `youtube` link of the song would suffice?

Regarding the logs, it just seems like the files are not being downloaded. Is your internet stable. The errors are `Request Time Out` which means the request to download the song timed out.

Either it was because of a lot of simultaneous requests to the server or it might be your internet connection.

**Comment by ArmagdoGaming** [comment]
@deepjyoti30 
Sure, the songs that I wanted to download were: 1:57 long; https://www.youtube.com/watch?v=sSQOLrUYLS8, 3:44; https://www.youtube.com/watch?v=kA9mwZ17uTw & 4:18; https://www.youtube.com/watch?v=pxF56x0I7lw. (These are the ones that I tried to download recently, I have tried other in the past, but they average at around 2:30 minutes, with a max of being 4 minutes long.)

As for my internet connection, everything else works fine. No lag in any games, either.
One thing to note is that after the two edits that I did, the third try took me straight to the download page, with around only 20 seconds of waiting. It just didn't work. The first two tries are the ones that took that long.

Might be because of the simultaneous requests to the server. I know my luck.

**Comment by deepjyoti30** [comment]
@ArmagdoGaming I was trying with one of the songs you shared. It seems like there is no metadata for that, have you been trying to add metadata manually every time you came across this issue?

**Comment by ArmagdoGaming** [comment]
Wow. Everything just...decided to work.
The two verified songs with metadata both downloaded, and the song without metadata did after adding manual metadata, as well.
I think that it was a problem because of all the request the server had to handle at that time.

Thank you for your help, and thank you for your time.
