### ISSUE TITLE
Get metadata automatically when a youtube url is given

### ISSUE THREAD

**Issue by aahnik** [deepjyoti30/ytmdl-web-v2#17]
When I enter the youtube url, i need to enter the name of the song in an extra step for metadata.

![image](https://user-images.githubusercontent.com/66209958/119826566-c8433c00-bf15-11eb-995b-ddb0711ea96d.png)

This can be automated. Fetching the metadata automatically would be great. There should be an option to edit the metadata after its fetched.

The name of the song can be fetched by - either scrapping the page of the URL, or using youtube API to get the title.

And that confirmation is pretty useless. A person who has entered an URL knows that he has entered an URL, and he intends to use it.

![image](https://user-images.githubusercontent.com/66209958/119826360-9205bc80-bf15-11eb-8f02-c6a15f544ddc.png)

**Comment by deepjyoti30** [comment]
@aahnik Regarding the confirmation, you can disable that in the settings.

For the automated part. I understand what you're trying to say. I have personally tried to implement that feature on the commandline version. However there is an issue. YouTube song titles mostly contain various other details about the song like name of artist or something similar. 

Also, metadata providers expect a proper song name else the results are weird (trust me on this).

This is why even on the commandline version we do not automate this part of the feature and it is still optional. Adding that functionality to the webapp would not be that feasible because of the above reason and that's why I skipped adding it when I was working on the v2 of the app.

If you feel like the feature is **very** important I can consider adding it but it would be hardly helpful. It would instead add another layer of user prompt because at the end the user would have to manually change the search term for metadata.

**Comment by aahnik** [comment]
> Regarding the confirmation, you can disable that in the settings.

Sorry for not exploring the settings and bothering you with silly questions.

> YouTube song titles mostly contain various other details about the song like name of artist or something similar.

This thought came to my mind. I honestly don't know any good answer to this problem. 

The songs which are available in YouTube Music, have proper metadata.

See this (scroll down till the end part of video description)

![image](https://user-images.githubusercontent.com/66209958/119828506-dabe7500-bf17-11eb-8315-0c5346183c80.png)

Not all songs are in YouTube Music, but most new songs or famous songs are. Some songs show not available in YouTube Music, but are playable in normal youtube. (I think those songs miss the metadata, and are not recognized as a song by youtube)

These stuff may be helpful

- https://ytmusicapi.readthedocs.io/en/latest/
- https://stackoverflow.com/a/57231482/15710459

**Comment by deepjyoti30** [comment]
@aahnik That YTMusic API actually looks pretty good. Just tested it with some songs and it is able to find lyrics for music videos as well.

I will try to add this to the commandline version. I guess on the next release, adding support for this can be expected.!

**Comment by deepjyoti30** [comment]
@aahnik If you would like to get a taste of this feature, you can check out the latest commits on the commandline version of the app.

I just added support to get the song title using `ytmusic`. You can [check this commit](https://github.com/deepjyoti30/ytmdl/commit/eeb680bdb8d104165954968c283ac5468c4dbe7f). It is pretty neat when it works.

If you do try it out and find some issue, you can open a new issue on that repo!

**Comment by deepjyoti30** [comment]
@aahnik This feature is now available on web.

This will be enabled by default but can be disabled from the settings. Do give it a try. You can report back here if there is some issue, or you can open a new one.

Closing this one.
