### ISSUE TITLE
360kbps download ability 

### ISSUE THREAD

**Issue by mizzunet** [deepjyoti30/ytmdl-web-v2#27]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description

Option to choose songs quality between 128kpbs and 360kbps

**Comment by deepjyoti30** [comment]
@mizzunet By default `320kbps` is selected.

I can add option for `360kbps` however you need to know this that YouTube quality is not exactly that high and when 320kbps or 360kbps is selected that's just ffmpeg converting the youtube quality to that bitrate. This means even if you go for 360kbps it wouldn't really improve the quality of the music.

Anyhow, is there some other reason you want 360kbps support other than the improved quality?

**Comment by mizzunet** [comment]
I downloaded a song, and it was 128kbps, maybe YT doesn't allow downloading that certain song at 360.

Well, with my earphone, it's easily differenicaible between qualities, that's why I'd like to.
:)

**Comment by deepjyoti30** [comment]
@mizzunet By default the webapp automatically downloads the song in the highest quality possible. After that if the song is supposed to be converted to a different format, then too the song is converted to the `320kbps` bitrate, however that doesn't change the quality of the audio.

Probably that's why you were able to differentiate between the qualities.

**Comment by mizzunet** [comment]
Oh, thank you for clarification. In this case this issue can be closed I guess
