### ISSUE TITLE
Stuck at "Extracting title from the entered URL..."

### ISSUE THREAD

**Issue by intr** [deepjyoti30/ytmdl-web-v2#71]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <Google Chrome>
- Version: Version 110.0.5481.180 (Official Build) (64-bit)

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description

When I try to download https://www.youtube.com/watch?v=iq3IOvDhrvM it gets stuck at "Extracting title from the entered URL..."

## Expected Behaviour

The song should be available for download.

**Comment by deepjyoti30** [comment]
@intr Thanks for reporting the issue. I am just seeing it happen now. I am looking into this. For now, searching the song with the name of the song is working so that can be used.

**Comment by deepjyoti30** [comment]
@intr This should be fixed in a few mins. Essentially the song you are entering is not found through yt-dlp and thus it was crashing. I have fixed the issue and from now on this scenario will be handled and reported back to the user.

I am closing this issue. In case you still see it, you can re-open it.
