### ISSUE TITLE
stuck on "your song is ready!" screen

### ISSUE THREAD

**Issue by blugreenz** [deepjyoti30/ytmdl-web-v2#85]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: chrome and firefox
- Version: (If possible)

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description
the page gets stuck on "your song is ready!" there is no option to download. 

## Expected Behaviour

button or options to download requested song should appear.

**Comment by BalintXHD** [comment]
same, tried with edge as well

**Comment by ghormadesoham** [comment]
This is reproducible with Brave browser as well.
HAR file attached.
Observations:
400 status code is returned for all video ids from https://apis.deepjyoti30.dev/v2/ytmdl/download
 Error message:

`{"detail":"Seems like the video ID passed is not valid."}`

[ytmdl.deepjyoti30.dev.har.txt](https://github.com/user-attachments/files/16620376/ytmdl.deepjyoti30.dev.har.txt)

**Comment by ghormadesoham** [comment]
Update:
Deepjyoti is actually already investigating this one. Thanks Deepjyoti.
For details see https://github.com/deepjyoti30/ytmdl/issues/299

**Comment by deepjyoti30** [comment]
Just to give you guys some updates here, the issue is happening because youtube is denying requests from all 3 nodes that ytmdl runs from. I have tried swapping IP's and passing cookies but neither of those 2 seem to be working.

These 3 are lifetime free nodes that oracle provides and because they don't cost me anything I am able to run ytmdl for free (except the cost of a self-hosted API gateway that handles these 3 nodes).

Thus switching to another provider or changing instances is not an option right now. Whatever solution comes up, will have to make sure that ytmdl can still run from these 3 nodes.

As of today, the cookies fix worked for a brief moment and I quickly made a patch release but that is not working anymore and even after passing the cookies, requests are being denied.

There are open conversations on this on yt-dlp repo if you guys are interested. I will continue to explore other options but YouTube seems to be hell bent on blocking such tools that provide easy access to their data.

**Comment by deepjyoti30** [comment]
All right guys, ytmdl is back-up. Enjoy!
