### ISSUE TITLE
Error when searching a song

### ISSUE THREAD

**Issue by rexdarelandig** [deepjyoti30/ytmdl-web-v2#9]
# Bug report

Seems to be working when you released it. But checking it now is not working.

![image](https://user-images.githubusercontent.com/57781286/110233208-71087d80-7f5d-11eb-8a85-e732ec3f2a2a.png)

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <>
- Version: (If possible)

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description

DESCRIBE THE ISSUE

## Expected Behaviour

SHARE WHAT THE EXPECTED BEHAVIOUR SHOULD BE

**Comment by deepjyoti30** [comment]
@rexdarelandig It seems like you're running the container locally??

Looking at the requests it seems like the it's an outdated package. I would suggest you to pull the latest container image and deploy it. Also, I just tested the official app and it worked totally fine!

**Comment by fine2006** [comment]
I have faced a similar issue running the git version locally:
```
googleads.g.doublecl…a!1&fsb=1&dtd=330:1 Failed to load resource: the server responded with a status of 403 ()
ads:1 Failed to load resource: the server responded with a status of 403 ()
ads:1 Failed to load resource: the server responded with a status of 403 ()
The script has an unsupported MIME type ('text/html').
localhost/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:8081/') with script ('http://localhost:8081/sw.js'): The script has an unsupported MIME type ('text/html').
ads:1 Failed to load resource: the server responded with a status of 403 ()
googleads.g.doublecl…ost%3A8081&dtd=28:1 Failed to load resource: the server responded with a status of 403 ()
ads:1 Failed to load resource: the server responded with a status of 403 ()
SongList.vue?c078:41 GET http://192.168.0.107:5000/v2/search?q=Hello net::ERR_CONNECTION_TIMED_OUT
asyncToGenerator.js?1da1:6 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by deepjyoti30** [comment]
@fine2006 As pointed by your logs, the git version is trying to access the API locally. If you want to test the app locally, try pulling the production branch.

Otherwise, you can just replace all the local networks calls to the API one.

Just find all the local calls by the following command:

```sh
grep "192.168.0.107" -r src
```

There should be three places where this API Url is set. Just replace them with `https://ytmdl-api-1.herokuapp.com/v2/ytmdl/`

I have plans of open sourcing the API for the app as well in the future.

Also in the above log, you can ignore all the errors related to google ads and service worker failing or such, those are happening because you're running the app locally, using the `production` image/branch would still be a better idea.

**Comment by fine2006** [comment]
I am in love with this app's design, and was trying to wrap it around through Tauri, and I want to allow the ads, what should I do?
So I think I should use the master branch right?
Also, the docker image works flawlessly

**Comment by deepjyoti30** [comment]
@fine2006 If you want to help with the ads, I don't think you can run them locally. In order for the ads to show up and the ads to earn some revenue it's important that the app runs on the domain that I have added in the configuration so locally the ads won't work.

I am not familiar with Tauri. It seems something like Electron but less bulkier?! If you want to create a distributable desktop app by using the web frontend then you should go with the production branch.

If you want to use it locally, you can use the master branch but you'll have to change the API call URL's to make sure the calls are made to the proper API.

If you could explain a bit about your motives about Tauri, I might be able to help a bit more with it!

**Comment by fine2006** [comment]
basically, tauri is much lighter, so compiling it on my computer won't take a day, which is a big relief 😛
Basically I want to make it easier to use the app, and have a better (cannnot connect to server message)
In browsers you can't do that, but storing webassets (atleast partially) locally could help in much better connection issues reporting.

(And I am super excited to tinker with stuff and make abominations 😁)

**Comment by deepjyoti30** [comment]
@fine2006 tour sounds good. You still didn't tell me if you want to share the app with others once it's deployed? If that's the case, as I said, use the production version.

If you want to do testing, use the master branch but make sure you change the API calls to the production API and it will start working. As of ads, I don't think they will work as it is.

I think in order to add ads to the app, I might need to register for some different kind of ads that are aimed at desktop/mobile apps? Not sure about that though!

**Comment by fine2006** [comment]
I would love to release the code on github and even a PR if you want!

**Comment by deepjyoti30** [comment]
@fine2006 That sounds great. You can create a dedicated repo for the desktop app and I will add links to that on the current repo.

**Comment by fine2006** [comment]
I think this issue is resolved and we should close this, and create a new issue for the app :)

**Comment by deepjyoti30** [comment]
@fine2006 Sure. You can go ahead and create a new issue related to the desktop app! I'll close this issue!
